// <auto-generated />
using System;
using EntityORM.DatabaseEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityORM.Migrations
{
    [DbContext(typeof(IdentityPmContext))]
    [Migration("20260425072155_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityORM.DatabaseEntity.Login", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UserRole")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Username")
                        .HasName("PK_IdentityPM_Login");

                    b.HasIndex(new[] { "Username" }, "IX_Login_Username");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("EntityORM.DatabaseEntity.Otpvalidate", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("Otp")
                        .HasColumnType("numeric(6,0)")
                        .HasColumnName("OTP");

                    b.Property<DateTime>("RequestedTime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("RetryAttempt")
                        .HasColumnType("numeric(2,0)");

                    b.HasKey("Username")
                        .HasName("PK_IdentityPM_OTPValidate");

                    b.HasIndex(new[] { "Username" }, "IX_OTPValidate_Username");

                    b.ToTable("OTPValidate", (string)null);
                });

            modelBuilder.Entity("EntityORM.DatabaseEntity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK_IdentityPM_User");

                    b.HasIndex(new[] { "Username" }, "IX_User_Username");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("EntityORM.DatabaseEntity.UserAuth", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username")
                        .HasName("PK_IdentityPM_UserAuth");

                    b.HasIndex(new[] { "Username" }, "IX_UserAuth_Username");

                    b.ToTable("UserAuth", (string)null);
                });

            modelBuilder.Entity("EntityORM.DatabaseEntity.Otpvalidate", b =>
                {
                    b.HasOne("EntityORM.DatabaseEntity.Login", "UsernameNavigation")
                        .WithOne("Otpvalidate")
                        .HasForeignKey("EntityORM.DatabaseEntity.Otpvalidate", "Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OTPValidate_Login");

                    b.Navigation("UsernameNavigation");
                });

            modelBuilder.Entity("EntityORM.DatabaseEntity.User", b =>
                {
                    b.HasOne("EntityORM.DatabaseEntity.Login", "UsernameNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Login_User");

                    b.Navigation("UsernameNavigation");
                });

            modelBuilder.Entity("EntityORM.DatabaseEntity.UserAuth", b =>
                {
                    b.HasOne("EntityORM.DatabaseEntity.Login", "UsernameNavigation")
                        .WithOne("UserAuth")
                        .HasForeignKey("EntityORM.DatabaseEntity.UserAuth", "Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAuth_Login");

                    b.Navigation("UsernameNavigation");
                });

            modelBuilder.Entity("EntityORM.DatabaseEntity.Login", b =>
                {
                    b.Navigation("Otpvalidate");

                    b.Navigation("UserAuth");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
