USE [IDENTITYSD]
GO

CREATE PROCEDURE DBO.UPSERT_USERPROFILEFROMJSON
    @JSONDATA NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRANSACTION;

    BEGIN TRY
        
        MERGE INTO USER_PERSONALDETAILS AS TARGET
        USING (
            SELECT 
                JSON_VALUE(@JSONDATA, '$.USERNAME') AS USERNAME,
                JSON_VALUE(@JSONDATA, '$.PERSONALDETAIL.BIRTHDATE') AS BIRTHDATE,
                JSON_VALUE(@JSONDATA, '$.PERSONALDETAIL.GENDER') AS GENDER,
                JSON_VALUE(@JSONDATA, '$.PERSONALDETAIL.LANGUAGEONE') AS LANGUAGEONE,
                JSON_VALUE(@JSONDATA, '$.PERSONALDETAIL.LANGUAGETWO') AS LANGUAGETWO,
                JSON_VALUE(@JSONDATA, '$.PERSONALDETAIL.LOCATION') AS LOCATION,
                JSON_VALUE(@JSONDATA, '$.PERSONALDETAIL.STATUS') AS [STATUS]
        ) AS SOURCE
        ON (TARGET.USERID = SOURCE.USERNAME)
        
        WHEN MATCHED THEN
            UPDATE SET 
                TARGET.BIRTHDATE = SOURCE.BIRTHDATE,
                TARGET.GENDER = SOURCE.GENDER,
                TARGET.LANGUAGEONE = SOURCE.LANGUAGEONE,
                TARGET.LANGUAGETWO = SOURCE.LANGUAGETWO,
                TARGET.LOCATION = SOURCE.LOCATION,
                TARGET.[STATUS] = SOURCE.[STATUS]
                
        WHEN NOT MATCHED THEN
            INSERT (USERID, BIRTHDATE, GENDER, LANGUAGEONE, LANGUAGETWO, LOCATION, [STATUS])
            VALUES (SOURCE.USERNAME, SOURCE.BIRTHDATE, SOURCE.GENDER, SOURCE.LANGUAGEONE, SOURCE.LANGUAGETWO, SOURCE.LOCATION, SOURCE.[STATUS]);

        MERGE INTO USER_EMPLOYMENTDETAILS AS TARGET
        USING (
            SELECT 
                USERID,
                EMPLOYERNAME,
                EMPLOYERCITY,
                ISCURRENTEMPLOYER,
                ROLE
            FROM OPENJSON(@JSONDATA, '$.EMPLOYMENTDETAIL')
            WITH (
                ID INT '$.ID',
                USERID INT '$.USERID',
                EMPLOYERNAME NVARCHAR(255) '$.EMPLOYERNAME',
                EMPLOYERCITY NVARCHAR(100) '$.EMPLOYERCITY',
                ISCURRENTEMPLOYER BIT '$.ISCURRENTEMPLOYER',
                ROLE NVARCHAR(100) '$.ROLE'
            )
        ) AS SOURCE
        ON (TARGET.USERID = SOURCE.USERID)
        
        WHEN MATCHED THEN
            UPDATE SET 
                TARGET.USERID = SOURCE.USERID,
                TARGET.EMPLOYERNAME = SOURCE.EMPLOYERNAME,
                TARGET.EMPLOYERCITY = SOURCE.EMPLOYERCITY,
                TARGET.ISCURRENTEMPLOYER = SOURCE.ISCURRENTEMPLOYER,
                TARGET.ROLE = SOURCE.ROLE
                
        WHEN NOT MATCHED THEN
            INSERT (USERID, EMPLOYERNAME, EMPLOYERCITY, ISCURRENTEMPLOYER, [ROLE])
            VALUES (SOURCE.USERID, SOURCE.EMPLOYERNAME, SOURCE.EMPLOYERCITY, SOURCE.ISCURRENTEMPLOYER, SOURCE.[ROLE]);

        MERGE INTO USER_LEARNDETAILS AS TARGET
        USING (
            SELECT 
                USERID,
                INSTITUTIONNAME,
                MAJOR,
                AWARD,
				STARTYEAR,
				ENDYEAR
            FROM OPENJSON(@JSONDATA, '$.LEARNDETAIL')
            WITH (
                USERID INT '$.USERID',
                INSTITUTIONNAME NVARCHAR(255) '$.INSTITUTIONNAME',
                MAJOR NVARCHAR(100) '$.MAJOR',
                AWARD NVARCHAR(100) '$.AWARD',
				STARTYEAR INT '$.STARTYEAR',
				ENDYEAR INT '$.ENDYEAR'
            )
        ) AS SOURCE
        ON (TARGET.USERID = SOURCE.USERID)
        
        WHEN MATCHED THEN
            UPDATE SET 
                TARGET.INSTITUTIONNAME = SOURCE.INSTITUTIONNAME,
                TARGET.MAJOR = SOURCE.MAJOR,
                TARGET.AWARD = SOURCE.AWARD,
                TARGET.STARTYEAR = SOURCE.STARTYEAR,
                TARGET.ENDYEAR = SOURCE.ENDYEAR

        WHEN NOT MATCHED THEN
            INSERT (USERID, INSTITUTIONNAME, MAJOR, AWARD, STARTYEAR, ENDYEAR)
            VALUES (SOURCE.USERID, SOURCE.INSTITUTIONNAME, SOURCE.MAJOR, SOURCE.AWARD, SOURCE.STARTYEAR, SOURCE.ENDYEAR);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        -- ROLLBACK IF ANY ERROR OCCURS DURING THE BATCH UPSERT
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        -- RAISE THE ERROR TO THE CALLING APPLICATION
        THROW;
    END CATCH
END;
GO